

GET https://localhost:8000/matchmaking
Authorization: Token 24f6656ab4efc88e8a456b3ffe1899d6c8a0e957
# Profile

###

GET https://localhost:8000/pong-2p
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029

###

GET https://localhost:8000/account/AI
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029

###

GET https://localhost:8000/account
Authorization: Token 58ecdb02b337cb800e9827172595c368b752c8ea

# Friends

###

GET https://localhost:8000/account/1/image
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029

###

POST https://localhost:8000/friend-request/send
Authorization: Token 58ecdb02b337cb800e9827172595c368b752c8ea
Content-Type: application/json

{
    "to_user": 29
}

###

GET https://localhost:8000/friend-request/list
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029

###

user1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58
user2
Authorization: Token 1a3d6fe4659ff8d6c8c40c244f4404f0d7079990
###

POST https://localhost:8000/friend-request/respond/1
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029
Content-Type: application/json

{
    "accept": true
}

###

POST https://localhost:8000/friend-remove/1
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029

###

GET https://localhost:8000/register HTTP/1.1
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029

###

# User update

###

PUT https://localhost:8000/account/update
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="pfp"; filename="1.jpg"
Content-Type: image/jpeg

< ./kitten.jpg
--boundary--

###

GET https://localhost:8000/account/1/image
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029

###

GET https://localhost:8000/account/1/image
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029

###

PUT https://localhost:8000/account/change-username HTTP/1.1
Authorization: Token 23889478f9d7ea0412781b2c996e6072c30ba029
Content-Type: application/json

{
    "username": "testUser1"
}

###

PUT https://localhost:8000/account/change-password HTTP/1.1
Authorization: Token d93892640657540dbe278efbc4b618cedd5203d0
Content-Type: application/json

{
    "password": "test"
}

###

POST https://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "testUser2",
    "password": "testPassword"
}

###

POST https://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "testUser2",
    "password": "testPassword"
}

###

# Matches pong 2p

###

GET https://localhost:8000/pong-2p HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801


###

POST https://localhost:8000/pong-2p HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801
Content-Type: application/json

{
    "player1": 1,
    "player1Score": 1,
    "player2Score": 6
}

###

POST https://localhost:8000/pong-2p HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801, Token d7666b33106ca023ac17cd750f2074b86605bab2
Content-Type: application/json

{
    "player1": 1,
    "player1Score": 3,
    "player2": 2,
    "player2Score": 2
}

###

GET https://localhost:8000/pong-2p/2 HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801

###

# Matches pong 4p

###

GET https://localhost:8000/pong-4p HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801

###

POST https://localhost:8000/pong-4p HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801
Content-Type: application/json

{
    "player1": 1,
    "player1Score": 0,
    "player2Score": 2
}

###

POST https://localhost:8000/pong-4p HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801
Content-Type: application/json

{
    "player1": 2,
    "player1Score": 3,
    "player2": 1,
    "player2Score": 2,
    "player3": 1,
    "player3Score": 2
}

###

GET https://localhost:8000/pong-4p/1 HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801

###

# Matches gonp 2p

###

GET https://localhost:8000/gonp-2p HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801


###

POST https://localhost:8000/gonp-2p HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801
Content-Type: application/json

{
    "player1": 1,
    "player1Score": 3,
    "player2Score": 2
}

###

POST https://localhost:8000/gonp-2p HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801, Token d7666b33106ca023ac17cd750f2074b86605bab2
Content-Type: application/json

{
    "player1": 1,
    "player1Score": 3,
    "player2": 2,
    "player2Score": 2
}

###

GET https://localhost:8000/gonp-2p/2 HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801

###

# CSRF TOKEN

###

GET https://localhost:8000/csrf-token HTTP/1.1

###

# Account requests

###

GET https://localhost:8000/register HTTP/1.1
Authorization: Token dfe76012f69dcc820faaecd60fa48d3667415801

###

POST https://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "user": {
        "username": "1515",
        "password": "1515"
    }
}

###

POST https://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "user": {
        "username": "testUser1",
        "password": "test"
    }
}

###

POST https://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "user": {
        "username": "testUser33",
        "password": "test"
    }
}

###

# Login

###

POST https://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "t6",
    "password": "t"
}

###

POST https://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "testUser1",
    "password": "testPassword"
}

###

POST https://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "newacc",
    "password": "newacc"
}

###


POST https://localhost:8000/login HTTP/1.1

###
