# Profile

GET http://localhost:8000/account
Authorization: Token e3770a085d86b87b6c2cb1d78d684eec69009a18

# Friends

###

POST http://localhost:8000/friend-request/send
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58
Content-Type: application/json

{
    "to_user": 2
}

###

GET http://localhost:8000/friend-request/list
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58

###

user1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58
user2
Authorization: Token 1a3d6fe4659ff8d6c8c40c244f4404f0d7079990
###

POST http://localhost:8000/friend-request/respond/3
Authorization: Token 1a3d6fe4659ff8d6c8c40c244f4404f0d7079990
Content-Type: application/json

{
    "accept": true
}

###

POST http://localhost:8000/friend-remove/1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58

###

GET http://localhost:8000/register HTTP/1.1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58

###

# User update

###

PUT http://localhost:8000/account/update HTTP/1.1
Authorization: Token 026f7008cd7cd287a4c934e0896316ae6bca3efa
Content-Type: application/json

{
    "wins": 14,
    "losses": 5
}

###

PUT http://localhost:8000/account/change-username HTTP/1.1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58
Content-Type: application/json

{
    "username": "testUser1"
}

###

PUT http://localhost:8000/account/change-password HTTP/1.1
Authorization: Token 026f7008cd7cd287a4c934e0896316ae6bca3efa
Content-Type: application/json

{
    "password": "testPassword"
}

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "testUser1",
    "password": "testpass"
}

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "testUser2",
    "password": "testPassword"
}

###

# Matches pong 2p

###

GET http://localhost:8000/pong-2p HTTP/1.1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58


###

POST http://localhost:8000/pong-2p HTTP/1.1
Authorization: Token 855ba830c100c7f927c41d406592d58319bd0240
Content-Type: application/json

{
    "player1": 1,
    "player1Score": 3,
    "player2Score": 2
}

###

POST http://localhost:8000/pong-2p HTTP/1.1
Authorization: Token 855ba830c100c7f927c41d406592d58319bd0240, Token 1a3d6fe4659ff8d6c8c40c244f4404f0d7079990
Content-Type: application/json

{
    "player1": 1,
    "player1Score": 3,
    "player2": 2,
    "player2Score": 2
}

###

GET http://localhost:8000/pong-2p/1 HTTP/1.1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58

###

# Matches pong 4p

###

GET http://localhost:8000/pong-4p HTTP/1.1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58

###

POST http://localhost:8000/pong-4p HTTP/1.1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58
Content-Type: application/json

{
    "player1": 2,
    "player1Score": 3,
    "player2Score": 2
}

###

POST http://localhost:8000/pong-4p HTTP/1.1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58, Token 1a3d6fe4659ff8d6c8c40c244f4404f0d7079990
Content-Type: application/json

{
    "player1": 1,
    "player1Score": 3,
    "player2": 2,
    "player2Score": 2
}

###

GET http://localhost:8000/pong-4p/1 HTTP/1.1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58

###

# CSRF TOKEN

###

GET http://localhost:8000/csrf-token HTTP/1.1

###

# Account requests

###

GET http://localhost:8000/register HTTP/1.1
Authorization: Token 5a835616857d3fe58ea7c7967279724af5507a58

###

POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "user": {
        "username": "testUser1",
        "password": "testPassword"
    }
}

###

POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "user": {
        "username": "testUser2",
        "password": "testPassword"
    }
}

###

POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "user": {
        "username": "testUser3",
        "password": "testPassword"
    }
}

###

# Login

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "FakeUser",
    "password": "testPassword"
}

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "testUser1",
    "password": "testPassword"
}

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "testUser2",
    "password": "testPassword"
}

###


POST http://localhost:8000/login HTTP/1.1

###