# Generated by Django 5.0.6 on 2024-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_account_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, to='login.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='pfp',
            field=models.ImageField(upload_to='login/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
