# Generated by Django 5.0.7 on 2024-07-26 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_account_pfp'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game1_player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game1_player1', to='login.account'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game1_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game1_player2', to='login.account'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game2_player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game2_player1', to='login.account'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game2_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game2_player2', to='login.account'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game3_player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game3_player1', to='login.account'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game3_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game3_player2', to='login.account'),
        ),
    ]
