# Generated by Django 5.1 on 2024-08-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gonp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gonp_4p',
        ),
    ]
