# Generated by Django 5.0.6 on 2024-06-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_alter_account_friends_alter_account_losses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('losers', models.ManyToManyField(related_name='lost_games', to='login.account')),
                ('winners', models.ManyToManyField(related_name='won_games', to='login.account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
