# Generated by Django 5.0.6 on 2024-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winners', models.CharField(max_length=110)),
                ('losers', models.CharField(max_length=110)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
