# Generated by Django 5.0.6 on 2024-06-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_account_friends_alter_account_losses_and_more'),
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='losers',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winners',
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.account')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', through='pong.MatchPlayer', to='login.account'),
        ),
    ]
