# Generated by Django 5.0.6 on 2024-06-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_account_friends_alter_account_losses_and_more'),
        ('pong', '0002_remove_match_losers_remove_match_winners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='login.account'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='login.account'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2Score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MatchPlayer',
        ),
    ]
