# Generated by Django 5.0.6 on 2024-06-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_account_friends_alter_account_losses_and_more'),
        ('pong', '0003_remove_match_players_match_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='login.account'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='login.account'),
        ),
    ]
