# Generated by Django 5.0.6 on 2024-07-02 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_account_options_friendrequest'),
        ('pong', '0005_alter_match_player1_alter_match_player2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pong_4p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player1Score', models.IntegerField(default=0)),
                ('player2Score', models.IntegerField(default=0)),
                ('player3Score', models.IntegerField(default=0)),
                ('player4Score', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_4p_p1', to='login.account')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_4p_p2', to='login.account')),
                ('player3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_4p_p3', to='login.account')),
                ('player4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_4p_p4', to='login.account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
